### ISSUE TITLE
ovmf (efi) booting not working on all "machines"

### ISSUE THREAD

**Issue by cycl0ne** [Limine-Bootloader/limine-c-template#13]
Not sure if i put it here or in the OMVF Repo.

Test:
Clean clone of this template script.
make all
make run

results on 2 of 3 machines -> QEMU saying: Guest has not initialized the display (yet).

![image](https://github.com/user-attachments/assets/5c45a0be-b5d6-4617-9b9a-6f9f8d3bb121)

Machine 1: Github Codespace (Intel(R) Xeon(R) Platinum 8370C CPU) (not working)
Machine 2: Physical Windows 11 (Fujitsu with Intel CPU) on WSL (working)
Machine 3: Physical Windows 11 (AMD Machine) on WSL (not working)

afer some search in net, i stumbled on a redit post, it was said, that the omvf could be busted, and one should try this one:
https://github.com/Absurdponcho/PonchoOS/tree/main/OVMFbin

with this downloaded : OVMF_CODE-pure-efi.fd and then started with: 
qemu-system-x86_64 -M q35 -drive if=pflash,format=raw,unit=0,file=ovmf/OVMF_CODE-pure-efi.fd -cdrom template-x86_64.iso -m 2G -serial stdio

it runs into UEFI Shell (changing boot order -> bcfg boot mv 2 1 and then reset) it runs the cdrom.
Tried this with Machine 3, copied the file to Machine 1 (Github Codespace) and now all machines work. (codespace with the parameter: -display none of course)

Tried the typical things before:
* Clean git clone
* make clean
* make distclean

**Comment by Mintsuki** [comment]
Hi,

Thanks for reporting the issue, though, unfortunately, this is an issue that it is not possible to solve.

The problem is that I made the deliberate decision to only have this template work with the latest QEMU: 9.1+ as of the time of posting this.

It is basically not possible to ship/download OVMF versions that will work across the board, on all QEMU versions, and a lot of distros ship a lot of different versions, with some shipping really old ones (like Debian, Ubuntu).

Frankly, if anything, this is something that should be taken up with the QEMU and OVMF maintainers, not this template, as, short of literally detecting the QEMU version in the makefile and shipping some OVMF known to work with it (which would highly complicate the makefile for a template), there is no fix possible.

An alternative, that would at least work for x86-64, is to use the `run-bios`/`run-hdd-bios` make targets, as those will just avoid OVMF altogether.

**Comment by jasondyoungberg** [comment]
The qemu version requirement should probably be documented in the readme

**Comment by cycl0ne** [comment]
run-bios /run-hdd-bios works, but then ACPI V1 is only shown in Memory with RSDP. So no 64bit XSDP. 

But thanks for the info, i will have a look at the versions. At the moment im at work, so i can only tell:
Github Codespace uses: 
QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.29)
QEMU AMD Machine: version 6.2.0 (Debian 1:6.2+dfsg-2ubuntu6.23)
QEMU Fujitsu: Version 8.2.2

So yes, can confirm, 8.2.2 works and even newer. Interesting fact: Both Machines running WSL has Ubuntu 24.4, strange they have different versions.
@mintsuki i will write this down, if you like i can write some documentation.  Also for the other stuff i find.

**Comment by Mintsuki** [comment]
> i will write this down, if you like i can write some documentation. Also for the other stuff i find.

@cycl0ne that's fine, PRs are open
